### ISSUE TITLE
ဘာသာပြန် ပြင်ဆင်ရန်

### ISSUE THREAD

**Issue by knwin** [SeePuuYar/QGIS328-Manual-MM#4]
https://seepuuyar.github.io/QGIS328-Manual-MM/docs/user_manual/working_with_raster/raster_properties.html#temporal-properties

"temporal Temporal tab ကိုအသုံးပြုပြီး layer ၏ rendering ကို **အချိန်နှင့်အမျှ** ထိန်းချုပ်ခြင်းများလုပ်ဆောင်နိုင်ပါသည်။" 

https://docs.qgis.org/3.34/en/docs/user_manual/working_with_raster/raster_properties.html#temporal-properties

မူရင်း - The temporal Temporal tab provides options to control the rendering of the layer **over time**. စာသားရှိ over time  ကို ဘာသာပြန်ပုံသည် အဓိပ္ပါယ် မမိဟု ထင်ပါသည်။

**Comment by SeePuuYar** [comment]
_"temporal Temporal tab ကိုအသုံးပြုပြီး layer ၏ rendering ကို **အချိန်ဖြင့်** ထိန်းချုပ်ခြင်းများလုပ်ဆောင်နိုင်ပါသည်။"_ ဟုပြင်ဆင်ထားပါသည်
